[package]
name = "turbochess"
version = "0.2.0"
edition = "2021"
authors = ["UPL"]
description = "A chess move generator"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html